Repository GoogleCloudPlatform/gcsfuse, pull requests merged in 2023-12, with the labels that each got.

#1533 Export file cache metrics via stackdriver
  docs/metrics.md
  internal/cache/file/downloader/job.go
  internal/fs/wrappers/monitoring.go
  internal/gcsx/random_reader.go
  internal/monitor/reader.go
  internal/monitor/tags/tags.go
  internal/util/util.go
Labels: execute-perf-test

#1537 make log compression on by default
  internal/config/mount_config.go
  internal/config/yaml_parser_test.go
Labels: execute-integration-tests

#1523 Add destroy method to delete cache during unmounting
  internal/cache/file/cache_handler.go
  internal/cache/file/cache_handler_test.go
  internal/cache/file/downloader/downloader.go
  internal/cache/file/downloader/downloader_test.go
  internal/cache/util/util.go
  internal/fs/fs.go
  internal/fs/read_cache_test.go
Labels: execute-integration-tests

#1534 Wait for termination of async job during Cancel and Invalidate
  internal/cache/file/downloader/job.go
Labels: execute-integration-tests

#1553 dependabot-fixes
  go.mod
  go.sum
Labels: execute-perf-test, execute-integration-tests

#1552 upgrade to go 1.21.5
  Dockerfile
  perfmetrics/scripts/ml_tests/pytorch/run_model.sh
  perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
  perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
  perfmetrics/scripts/run_e2e_tests.sh
  tools/cd_scripts/e2e_test.sh
  tools/containerize_gcsfuse_docker/Dockerfile
  tools/package_gcsfuse_docker/Dockerfile
Labels: execute-perf-test, execute-integration-tests

#1540 Merge type-cache-ttl into stat-cache-ttl
  docs/semantics.md
  flags.go
  flags_test.go
Labels: execute-integration-tests

#1545 Add metadata-cache:ttl-secs config
  docs/semantics.md
  flags.go
  flags_test.go
  internal/config/mount_config.go
  internal/config/testdata/metadata_cache_config_invalid_ttl.yaml
  internal/config/testdata/metadata_cache_config_ttl-unset.yaml
  internal/config/testdata/valid_config.yaml
  internal/config/yaml_parser.go
  internal/config/yaml_parser_test.go
  internal/fs/caching_test.go
  main.go
  mount.go
  perfmetrics/scripts/ml_tests/pytorch/run_model.sh
  perfmetrics/scripts/read_cache/generate_yml_config.sh
  perfmetrics/scripts/read_cache/mount_gcsfuse.sh
Labels: execute-integration-tests

#1554 Change LRU in file cache on every request from kernel
  internal/cache/file/cache_handle.go
  internal/cache/file/cache_handle_test.go
  internal/cache/file/cache_handler_test.go
  internal/fs/read_cache_test.go
  internal/gcsx/random_reader.go
  perfmetrics/scripts/job_files/presubmit_perf_test.fio
Labels: execute-integration-tests

#1565 Adding log to print all configuration flags at start of gcs fuse mount
  internal/util/util.go
  internal/util/util_test.go
  main.go
  main_test.go
Labels: execute-integration-tests
