Repository GoogleCloudPlatform/gcsfuse, pull requests merged in 2024-06, with the labels that each got.

#1964 Close the reader of async job in file cache to have the closing debug logs
  internal/cache/file/downloader/job.go
Labels: execute-integration-tests

#1955 remove gcloud command from readonly e2e tests
  tools/integration_tests/readonly/copy_object_test.go
  tools/integration_tests/readonly/create_object_test.go
  tools/integration_tests/readonly/delete_object_test.go
  tools/integration_tests/readonly/list_objects_test.go
  tools/integration_tests/readonly/read_test.go
  tools/integration_tests/readonly/readonly_test.go
  tools/integration_tests/readonly/rename_object_test.go
  tools/integration_tests/readonly/stat_object_test.go
  tools/integration_tests/readonly/testdata/create_objects.sh
  tools/integration_tests/readonly/testdata/delete_objects.sh
  tools/integration_tests/readonly/write_test.go
Labels: execute-integration-tests

#1949 Move code in the main package to cmd package
  cmd/flags.go
  cmd/flags_test.go
  cmd/legacy_main.go
  cmd/legacy_main_test.go
  cmd/mount.go
  cmd/testdata/test_creds.json
  cmd/version.go
  main.go
  tools/build_gcsfuse/main.go
Labels: execute-integration-tests

#1978 Fix readonly --only-dir tests for GKE environment
  tools/integration_tests/readonly/readonly_test.go
Labels: execute-integration-tests

#1975 Fix security vulnerability by getting rid of text/template
  go.mod
  go.sum
  tools/config-gen/main.go
Labels: execute-perf-test, execute-integration-tests

#1982 Update direct dependencies
  go.mod
  go.sum
Labels: execute-perf-test, execute-integration-tests

#1977 Add progress logs for gcs: CreateObject
  internal/storage/bucket_handle.go
  internal/storage/debug_bucket.go
  internal/storage/gcs/bucket.go
  tools/integration_tests/log_content/file_upload_log_test.go
  tools/integration_tests/log_content/log_content_test.go
  tools/integration_tests/run_e2e_tests.sh
  tools/integration_tests/util/operations/file_operations.go
  tools/integration_tests/util/operations/string_operations.go
  tools/integration_tests/util/setup/setup.go
Labels: execute-integration-tests

#1987 Use text/template for code-generation
  go.mod
  go.sum
  tools/config-gen/main.go
Labels: execute-perf-test, execute-integration-tests

#1988 Added flag to enable crc check
  cmd/legacy_main_test.go
  internal/cache/file/cache_handle_test.go
  internal/cache/file/cache_handler_test.go
  internal/cache/file/downloader/downloader.go
  internal/cache/file/downloader/downloader_test.go
  internal/cache/file/downloader/job.go
  internal/cache/file/downloader/job_test.go
  internal/config/mount_config.go
  internal/config/testdata/valid_config.yaml
  internal/config/yaml_parser_test.go
  internal/fs/fs.go
  internal/gcsx/random_reader_test.go
Labels: execute-integration-tests

#1990 Parallel downloads config
  cmd/legacy_main_test.go
  internal/cache/file/cache_handler_test.go
  internal/cache/file/downloader/downloader.go
  internal/cache/file/downloader/downloader_test.go
  internal/cache/file/downloader/job.go
  internal/config/mount_config.go
  internal/config/testdata/file_cache_config/invalid_download_parallelism_per_file.yaml
  internal/config/testdata/file_cache_config/invalid_max_download_parallelism.yaml
  internal/config/testdata/file_cache_config/invalid_max_size_mb.yaml
  internal/config/testdata/file_cache_config/invalid_read_request_size_mb.yaml
  internal/config/testdata/valid_config.yaml
  internal/config/yaml_parser.go
  internal/config/yaml_parser_test.go
  internal/fs/fs.go
  internal/gcsx/random_reader_test.go
Labels: execute-integration-tests

#1938 fix flaky TestRangeReadsWithCacheHit test by reducing the file size
  tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go
  tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go
  tools/integration_tests/read_cache/setup_test.go
Labels: execute-integration-tests

#1996 Upgrading go lang to 1.22.4
  Dockerfile
  go.mod
  perfmetrics/scripts/ml_tests/pytorch/run_model.sh
  perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
  perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
  perfmetrics/scripts/read_cache/setup.sh
  tools/cd_scripts/e2e_test.sh
  tools/containerize_gcsfuse_docker/Dockerfile
  tools/integration_tests/run_e2e_tests.sh
  tools/package_gcsfuse_docker/Dockerfile
Labels: execute-perf-test

#2000 Use struct to bundle function parameters
  internal/cache/file/cache_handler_test.go
  internal/cache/file/downloader/downloader.go
  internal/cache/file/downloader/downloader_test.go
  internal/fs/fs.go
  internal/gcsx/random_reader_test.go
Labels: execute-integration-tests

#1989 Added code changes to add crc check for sequential download behind flag
  internal/cache/file/downloader/downloader_test.go
  internal/cache/file/downloader/job.go
  internal/cache/file/downloader/job_test.go
  internal/cache/util/testdata/emptyfile.txt
  internal/cache/util/testdata/validfile.txt
  internal/cache/util/util.go
  internal/cache/util/util_test.go
  internal/fs/local_modifications_test.go
  internal/gcsx/random_reader_test.go
  internal/storage/gcs/object.go
  internal/storage/storageutil/object_attrs.go
  internal/storage/storageutil/object_attrs_test.go
Labels: execute-integration-tests

#1995 Passing spread sheet id as param
  perfmetrics/scripts/continuous_test/gcp_ubuntu/build.sh
  perfmetrics/scripts/fetch_and_upload_metrics.py
  perfmetrics/scripts/gsheet/gsheet.py
  perfmetrics/scripts/ls_metrics/listing_benchmark.py
  perfmetrics/scripts/ls_metrics/run_ls_benchmark.sh
  perfmetrics/scripts/run_load_test_and_fetch_metrics.sh
Labels: execute-perf-test

#2004 passes cache config to job
  internal/cache/file/cache_handle_test.go
  internal/cache/file/downloader/downloader.go
  internal/cache/file/downloader/job.go
  internal/cache/file/downloader/job_test.go
Labels: execute-integration-tests

#2009 Update direct dependencies.
  go.mod
  go.sum
Labels: execute-perf-test

#1959 Convert gcloud operations in storage client - 1
  tools/integration_tests/implicit_dir/implicit_dir_test.go
  tools/integration_tests/implicit_dir/local_file_test.go
  tools/integration_tests/interrupt/interrupt_test.go
  tools/integration_tests/local_file/local_file_test.go
  tools/integration_tests/log_rotation/log_rotation_test.go
  tools/integration_tests/managed_folders/list_empty_managed_folders_test.go
  tools/integration_tests/managed_folders/managed_folders_test.go
  tools/integration_tests/managed_folders/test_helper.go
  tools/integration_tests/managed_folders/view_permissions_test.go
  tools/integration_tests/operations/operations_test.go
  tools/integration_tests/read_cache/remount_test.go
  tools/integration_tests/read_cache/setup_test.go
  tools/integration_tests/readonly_creds/readonly_creds_test.go
  tools/integration_tests/util/mounting/dynamic_mounting/dynamic_mounting.go
  tools/integration_tests/util/mounting/dynamic_mounting/testdata/create_bucket.sh
  tools/integration_tests/util/mounting/dynamic_mounting/testdata/delete_bucket.sh
  tools/integration_tests/util/setup/setup.go
Labels: execute-integration-tests

#1954 Delete folder api implementation
  internal/fs/inode/dir.go
  internal/gcsx/prefix_bucket.go
  internal/monitor/bucket.go
  internal/ratelimit/throttled_bucket.go
  internal/storage/bucket_handle.go
  internal/storage/bucket_handle_test.go
  internal/storage/caching/fast_stat_bucket.go
  internal/storage/control_client_wrapper.go
  internal/storage/debug_bucket.go
  internal/storage/fake/bucket.go
  internal/storage/gcs/bucket.go
  internal/storage/mock_bucket.go
  internal/storage/mock_control_client.go
  tools/integration_tests/operations/operations_test.go
Labels: execute-integration-tests

#2020 fix e2e test for hns bucket
  tools/integration_tests/operations/operations_test.go
  tools/integration_tests/run_e2e_tests.sh
Labels: execute-integration-tests

#2013 Making compute crc method context cancellable
  internal/cache/file/downloader/downloader_test.go
  internal/cache/file/downloader/job.go
  internal/cache/file/downloader/job_test.go
  internal/cache/util/util.go
  internal/cache/util/util_test.go
Labels: execute-integration-tests

#2003 Use 1.22 as the min Go version
  go.mod
Labels: execute-perf-test

#2028 Set crc32 when converting minobject to object
  internal/storage/storageutil/object_attrs.go
  internal/storage/storageutil/object_attrs_test.go
Labels: execute-integration-tests

#2005 Add parallel downloads job
  docs/metrics.md
  internal/cache/file/downloader/downloader_test.go
  internal/cache/file/downloader/job.go
  internal/cache/file/downloader/job_test.go
  internal/cache/file/downloader/parallel_downloads_job.go
  internal/cache/file/downloader/parallel_downloads_job_test.go
  internal/util/util.go
Labels: execute-integration-tests

#2027 Make Wait for Download false for all read scenarios when parallel downloads is true
  internal/cache/file/cache_handle.go
  internal/cache/file/cache_handle_test.go
  internal/cache/file/downloader/job.go
  internal/cache/file/downloader/job_test.go
Labels: execute-integration-tests

#1993 Support fstab mount with hyphens
  tools/mount_gcsfuse/main.go
  tools/mount_gcsfuse/main_test.go
Labels: execute-integration-tests

#2032 Implement limit on max-concurrency.
  internal/cache/file/cache_handle_test.go
  internal/cache/file/downloader/downloader.go
  internal/cache/file/downloader/jm_parallel_downloads_test.go
  internal/cache/file/downloader/job.go
  internal/cache/file/downloader/job_test.go
  internal/cache/file/downloader/parallel_downloads_job.go
  internal/cache/file/downloader/test_util.go
Labels: execute-integration-tests

#2046 Add max-download-parallelism validation
  internal/config/testdata/file_cache_config/invalid_zero_max_download_parallelism.yaml
  internal/config/yaml_parser.go
  internal/config/yaml_parser_test.go
Labels: execute-integration-tests

#2034 Ignore interrupts by default
  cfg/config.go
  cmd/flags.go
  docs/troubleshooting.md
  internal/config/mount_config.go
  internal/config/yaml_parser_test.go
  tools/config-gen/params.yaml
  tools/integration_tests/interrupt/interrupt_test.go
Labels: execute-integration-tests

#2041 adds get folder method in bucket.go
  internal/gcsx/prefix_bucket.go
  internal/gcsx/prefix_bucket_test.go
  internal/monitor/bucket.go
  internal/ratelimit/throttled_bucket.go
  internal/storage/bucket_handle.go
  internal/storage/bucket_handle_test.go
  internal/storage/caching/fast_stat_bucket.go
  internal/storage/control_client_wrapper.go
  internal/storage/debug_bucket.go
  internal/storage/fake/bucket.go
  internal/storage/gcs/bucket.go
  internal/storage/mock_bucket.go
  internal/storage/mock_control_client.go
Labels: execute-integration-tests

#2039 fix gcloud install
  perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/tpc_build.sh
  tools/integration_tests/run_e2e_tests.sh
Labels: execute-integration-tests

#2056 Use atleast 1 goroutine for async job
  internal/cache/file/downloader/jm_parallel_downloads_test.go
  internal/cache/file/downloader/parallel_downloads_job.go
Labels: execute-integration-tests

#2019 Add more tests (unit, composite) tests for parallel downloads
  internal/cache/file/downloader/job_test.go
  internal/cache/file/downloader/parallel_downloads_job_test.go
  internal/fs/read_cache_test.go
Labels: execute-integration-tests, parallel-downloads

#2064 Rename parallel downloads flags
  cfg/config.go
  cmd/legacy_main_test.go
  internal/cache/file/cache_handle_test.go
  internal/cache/file/cache_handler_test.go
  internal/cache/file/downloader/downloader.go
  internal/cache/file/downloader/downloader_test.go
  internal/cache/file/downloader/jm_parallel_downloads_test.go
  internal/cache/file/downloader/job.go
  internal/cache/file/downloader/job_test.go
  internal/cache/file/downloader/parallel_downloads_job.go
  internal/cache/file/downloader/parallel_downloads_job_test.go
  internal/config/mount_config.go
  internal/config/testdata/file_cache_config/invalid_download_chunk_size_mb.yaml
  internal/config/testdata/file_cache_config/invalid_download_parallelism_per_file.yaml
  internal/config/testdata/file_cache_config/invalid_max_parallel_downloads.yaml
  internal/config/testdata/file_cache_config/invalid_parallel_downloads_per_file.yaml
  internal/config/testdata/file_cache_config/invalid_read_request_size_mb.yaml
  internal/config/testdata/file_cache_config/invalid_zero_max_parallel_downloads.yaml
  internal/config/testdata/valid_config.yaml
  internal/config/yaml_parser.go
  internal/config/yaml_parser_test.go
  internal/fs/read_cache_test.go
  internal/gcsx/random_reader_test.go
  tools/config-gen/params.yaml
Labels: execute-integration-tests

#2047 Use default MaxDownloadParallelism based on number of CPU cores
  internal/config/config_util.go
  internal/config/config_util_test.go
  internal/config/mount_config.go
  internal/config/yaml_parser_test.go
Labels: execute-integration-tests

#2073 Setting defaults for parallel downloads
  cfg/config.go
  internal/config/mount_config.go
  internal/config/yaml_parser_test.go
  tools/config-gen/params.yaml
Labels: execute-integration-tests

#2015 Use truncate and remove function while eviction from job during CRC check
  internal/cache/file/cache_handler.go
  internal/cache/file/downloader/job.go
  internal/cache/util/util.go
  internal/cache/util/util_test.go
Labels: execute-integration-tests, parallel-downloads

#2017 Refactor deletefolder API
  internal/config/yaml_parser.go
  internal/fs/inode/dir.go
  internal/gcsx/prefix_bucket_test.go
  internal/storage/bucket_handle.go
  internal/storage/bucket_handle_test.go
  tools/integration_tests/implicit_dir/implicit_dir_test.go
  tools/integration_tests/operations/operations_test.go
  tools/integration_tests/util/setup/implicit_and_explicit_dir_setup/implicit_and_explicit_dir_setup.go
  tools/integration_tests/util/setup/setup.go
Labels: execute-integration-tests

#2062 [CLI Config Parity] migrate log-file legacy flag/config to new config
  cmd/flags.go
  cmd/flags_test.go
  cmd/legacy_main.go
  cmd/legacy_param_mapper_test.go
  internal/config/config_util.go
  internal/config/config_util_test.go
  internal/logger/logger.go
  internal/logger/logger_test.go
  tools/integration_tests/log_rotation/log_rotation_test.go
Labels: execute-integration-tests

#2076 Fix test in GKE environment
  tools/integration_tests/util/setup/setup.go
Labels: execute-integration-tests

#2078 Use a viper instance for deserialization
  cfg/config.go
  cmd/root.go
  cmd/root_test.go
  tools/config-gen/config.tpl
Labels: execute-integration-tests

#2083 Revert "Move KernelListCacheTtlSecs to List
  cmd/legacy_main_test.go
  internal/config/config_util.go
  internal/config/config_util_test.go
  internal/config/mount_config.go
  internal/config/testdata/file_system_config/invalid_kernel_list_cache_ttl.yaml
  internal/config/testdata/file_system_config/unset_kernel_list_cache_ttl.yaml
  internal/config/testdata/file_system_config/unsupported_large_kernel_list_cache_ttl.yaml
  internal/config/testdata/file_system_config/valid_kernel_list_cache_ttl.yaml
  internal/config/testdata/list_config/unset_kernel_list_cache_ttl.yaml
  internal/config/yaml_parser.go
  internal/config/yaml_parser_test.go
Labels: execute-integration-tests
