Repository GoogleCloudPlatform/gcsfuse, pull requests merged in 2024-07, with the labels that each got.

#2086 upgrade dependencies
  go.mod
  go.sum
Labels: execute-perf-test, execute-integration-tests

#2089 Migrate a few flags to the new config
  cfg/types.go
  cmd/flags.go
  cmd/legacy_main.go
  cmd/legacy_main_test.go
  cmd/mount.go
  internal/mount/flag.go
  internal/storage/storage_handle.go
  internal/storage/storage_handle_test.go
  internal/storage/storageutil/client.go
  internal/storage/storageutil/test_util.go
Labels: execute-integration-tests

#2093 Remove unused fields from flagStorage struct
  cmd/flags.go
  cmd/flags_test.go
  cmd/legacy_main_test.go
  cmd/legacy_param_mapper_test.go
  cmd/mount.go
  internal/fs/fs.go
Labels: execute-integration-tests

#2095 Migrate most flags to the new config
  cfg/config_util.go
  cmd/flags.go
  cmd/flags_test.go
  cmd/legacy_main.go
  cmd/legacy_main_test.go
  cmd/legacy_param_mapper_test.go
  cmd/mount.go
Labels: execute-integration-tests

#2045 Implement rename folder 1
  internal/gcsx/prefix_bucket.go
  internal/monitor/bucket.go
  internal/ratelimit/throttled_bucket.go
  internal/storage/bucket_handle.go
  internal/storage/caching/fast_stat_bucket.go
  internal/storage/control_client_wrapper.go
  internal/storage/debug_bucket.go
  internal/storage/fake/bucket.go
  internal/storage/gcs/bucket.go
  internal/storage/mock_bucket.go
  internal/storage/mock_control_client.go
Labels: execute-integration-tests

#2098 Fix default for experimental-grpc-conn-pool-size
  cfg/config.go
  tools/config-gen/params.yaml
Labels: execute-integration-tests

#2113 Replace EnableHNS type with bool
  internal/config/mount_config.go
  internal/storage/storageutil/client.go
Labels: execute-integration-tests

#2128 Fast stat bucket changes
  internal/cache/metadata/stat_cache.go
  internal/cache/metadata/stat_cache_test.go
  internal/gcsx/prefix_bucket.go
  internal/gcsx/prefix_bucket_test.go
  internal/monitor/bucket.go
  internal/ratelimit/throttled_bucket.go
  internal/storage/bucket_handle.go
  internal/storage/bucket_handle_test.go
  internal/storage/caching/fast_stat_bucket.go
  internal/storage/caching/mock_gcscaching/mock_stat_cache.go
  internal/storage/debug_bucket.go
  internal/storage/fake/bucket.go
  internal/storage/gcs/bucket.go
  internal/storage/gcs/folder.go
  internal/storage/mock_bucket.go
Labels: execute-integration-tests

#2088 [Dependabot Alert] Upgrade pip dependencies and requirements file to fix urllib severities
  perfmetrics/scripts/bigquery/requirements.in
  perfmetrics/scripts/bigquery/requirements.txt
  perfmetrics/scripts/requirements.in
  perfmetrics/scripts/requirements.txt
Labels: execute-perf-test

#2129 Move enableHNS to new config
  cmd/legacy_main.go
Labels: execute-integration-tests

#2136 Add an example of valid location value in integration tests
  tools/integration_tests/run_e2e_tests.sh
Labels: execute-integration-tests

#2135 Fix imports as part of build
  Makefile
  tools/integration_tests/mounting/gcsfuse_darwin_test.go
  tools/integration_tests/mounting/gcsfuse_test.go
Labels: execute-integration-tests

#2138 Stat cache bucket changes
  internal/storage/caching/fast_stat_bucket.go
  internal/storage/caching/fast_stat_bucket_test.go
  internal/storage/mock_bucket.go
Labels: execute-integration-tests

#2118 Add parallel download configuration to existing read cache e2e tests
  tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go
  tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go
  tools/integration_tests/read_cache/disabled_cache_ttl_test.go
  tools/integration_tests/read_cache/helpers_test.go
  tools/integration_tests/read_cache/local_modification_test.go
  tools/integration_tests/read_cache/range_read_test.go
  tools/integration_tests/read_cache/read_only_test.go
  tools/integration_tests/read_cache/remount_test.go
  tools/integration_tests/read_cache/setup_test.go
  tools/integration_tests/read_cache/small_cache_ttl_test.go
  tools/integration_tests/util/client/gcs_helper.go
Labels: execute-integration-tests

#2146 fix only dir mounting test's success code
  tools/integration_tests/util/mounting/only_dir_mounting/only_dir_mounting.go
Labels: execute-integration-tests

#2140 Kernel cache list tests in list large directory e2e tests
  tools/integration_tests/list_large_dir/list_dir_with_twelve_thousand_files_test.go
  tools/integration_tests/list_large_dir/list_large_dir_test.go
  tools/integration_tests/run_e2e_tests.sh
  tools/integration_tests/run_tests_mounted_directory.sh
  tools/integration_tests/util/setup/setup.go
Labels: execute-integration-tests

#2152 Functional test infinite kernel cache ttl - 1
  tools/integration_tests/kernel-list-cache/infinite_kernel_list_cache_test.go
Labels: execute-integration-tests

#2148 Functional test for kernel-cache-ttl=0
  tools/integration_tests/kernel-list-cache/disabled_kernel_list_cache_test.go
Labels: execute-integration-tests

#2153 Functional test with finite kernel cache ttl
  tools/integration_tests/kernel-list-cache/finite_kernel_list_cache_test.go
Labels: execute-integration-tests

#2154 Functional test infinite kernel cache ttl - 2
  tools/integration_tests/kernel-list-cache/finite_kernel_list_cache_test.go
  tools/integration_tests/kernel-list-cache/infinite_kernel_list_cache_test.go
Labels: execute-integration-tests

#2155 Adding e2e test for kernel-list-cache concurrency test
  tools/integration_tests/concurrent_operations/concurrent_listing_test.go
  tools/integration_tests/concurrent_operations/setup_test.go
  tools/integration_tests/run_e2e_tests.sh
Labels: execute-integration-tests

#2156 Functional test infinite kernel cache ttl - 3
  tools/integration_tests/kernel-list-cache/infinite_kernel_list_cache_test.go
Labels: execute-integration-tests

#2159 Functional test kernel cache infinite ttl 4
  tools/integration_tests/kernel-list-cache/infinite_kernel_list_cache_test.go
Labels: execute-integration-tests

#2139 Function to convert controlpb.folder attributes to gcs.Folder
  internal/storage/bucket_handle.go
  internal/storage/bucket_handle_test.go
  internal/storage/gcs/folder.go
  internal/storage/gcs/folder_test.go
Labels: execute-integration-tests

#2162 adds hns check in dir.go
  internal/fs/fs.go
  internal/fs/handle/dir_handle_test.go
  internal/fs/inode/dir.go
  internal/fs/inode/dir_test.go
  internal/fs/inode/explicit_dir.go
Labels: execute-integration-tests

#2143 Add kernel list cache tests to operations package
  tools/integration_tests/operations/operations_test.go
  tools/integration_tests/run_tests_mounted_directory.sh
Labels: execute-integration-tests

#2169 Hns pre submit test fix
  internal/fs/inode/dir.go
Labels: execute-integration-tests

#2165 Create folder integration - 1
  internal/gcsx/prefix_bucket.go
  internal/monitor/bucket.go
  internal/ratelimit/throttled_bucket.go
  internal/storage/bucket_handle.go
  internal/storage/caching/fast_stat_bucket.go
  internal/storage/control_client_wrapper.go
  internal/storage/debug_bucket.go
  internal/storage/fake/bucket.go
  internal/storage/gcs/bucket.go
  internal/storage/mock_bucket.go
  internal/storage/mock_control_client.go
Labels: execute-integration-tests

#2180 Concurrent test: pre-create file to avoid input/output error
  tools/integration_tests/concurrent_operations/concurrent_listing_test.go
Labels: execute-integration-tests

#2158 fix flakiness in read cache parallel download test
  tools/integration_tests/read_cache/helpers_test.go
  tools/integration_tests/util/client/gcs_helper.go
Labels: execute-integration-tests

#2131 Integrating max retry attempts with client and changing the default retry attempts to 0
  cfg/config.go
  cmd/flags.go
  cmd/legacy_main.go
  cmd/legacy_param_mapper.go
  internal/config/mount_config.go
  internal/storage/storage_handle.go
  internal/storage/storage_handle_test.go
  internal/storage/storageutil/client.go
  internal/storage/storageutil/test_util.go
  tools/config-gen/params.yaml
Labels: execute-integration-tests

#2170 Rename folder invalidating stat cache
  internal/cache/lru/lru.go
  internal/cache/lru/lru_test.go
  internal/cache/metadata/stat_cache.go
  internal/cache/metadata/stat_cache_test.go
  internal/storage/caching/fast_stat_bucket.go
  internal/storage/caching/fast_stat_bucket_test.go
  internal/storage/caching/mock_gcscaching/mock_stat_cache.go
  internal/storage/mock_bucket.go
Labels: execute-integration-tests

#2182 [Read Cache parallel downloads test] Add tests to validate async job chunk size
  tools/integration_tests/read_cache/helpers_test.go
  tools/integration_tests/read_cache/job_chunk_test.go
  tools/integration_tests/util/log_parser/json_parser/read_logs/helpers.go
  tools/integration_tests/util/log_parser/json_parser/read_logs/json_job_log_parser.go
  tools/integration_tests/util/log_parser/json_parser/read_logs/json_job_log_parser_test.go
  tools/integration_tests/util/log_parser/json_parser/read_logs/structure.go
Labels: execute-integration-tests

#2187 [HNS] Add method to parallely call stat and get folder object
  internal/cache/metadata/stat_cache.go
  internal/cache/metadata/stat_cache_test.go
  internal/fs/inode/dir.go
  internal/fs/inode/dir_test.go
  internal/storage/fake/bucket.go
  internal/storage/gcs/folder.go
  internal/storage/gcs/folder_test.go
Labels: execute-integration-tests

#2177 Create folder implementation - 2
  internal/storage/bucket_handle.go
  internal/storage/bucket_handle_test.go
  internal/storage/fake_storage_util.go
Labels: execute-integration-tests

#2184 DeleteFolder fast stat bucket fix.
  internal/storage/caching/fast_stat_bucket.go
  internal/storage/caching/fast_stat_bucket_test.go
  internal/storage/mock_bucket.go
Labels: execute-integration-tests

#2191 Implement rename folder function in dir Inode interface
  internal/fs/inode/base_dir.go
  internal/fs/inode/dir.go
  internal/fs/inode/dir_test.go
  internal/storage/fake/bucket.go
Labels: execute-integration-tests

#2157 Rename kernel-list-cache directory to follow underscore pattern
  tools/integration_tests/kernel_list_cache/disabled_kernel_list_cache_test.go
  tools/integration_tests/kernel_list_cache/finite_kernel_list_cache_test.go
  tools/integration_tests/kernel_list_cache/infinite_kernel_list_cache_test.go
  tools/integration_tests/kernel_list_cache/setup_test.go
  tools/integration_tests/run_e2e_tests.sh
Labels: execute-integration-tests

#2195 Bump Dependabot PRs
  Dockerfile
  go.mod
  go.sum
Labels: execute-perf-test, execute-integration-tests

#2196 Python dependencies
  perfmetrics/scripts/load_tests/python/requirements.txt
  perfmetrics/scripts/requirements.txt
Labels: execute-perf-test, execute-integration-tests

#2209 Upgrade gem lock dependency
  tools/gem_dependency/Gemfile.lock
Labels: execute-perf-test, execute-integration-tests

#2215 Add kernel-cache-ttl=0 in e2e tests
  tools/integration_tests/concurrent_operations/setup_test.go
Labels: execute-integration-tests

#2115 Pass the bucket and mountpoint into the mount fn
  cmd/legacy_main.go
  cmd/root.go
  cmd/root_test.go
  main.go
Labels: execute-integration-tests

#2189 disable experimental test run for presubmit test
  perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/build.sh
  perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/tpc_build.sh
  perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
  tools/integration_tests/operations/operations_test.go
  tools/integration_tests/run_e2e_tests.sh
  tools/integration_tests/util/setup/setup.go
Labels: execute-integration-tests

#2222 Fix kokoro e2e tests
  tools/integration_tests/concurrent_operations/setup_test.go
Labels: execute-integration-tests

#2207 Lookup for hns 1
  internal/cache/metadata/stat_cache.go
  internal/cache/metadata/stat_cache_test.go
  internal/fs/inode/dir.go
  internal/fs/inode/hns_dir_test.go
  internal/storage/bucket_handle.go
  internal/storage/gcs/folder.go
  internal/storage/gcs/folder_test.go
  internal/storage/testify_mock_bucket.go
Labels: execute-integration-tests

#2163 [bug fix] Kernel list cache remove directory operation fails when files are created on GCS
  internal/fs/fs.go
  internal/fs/inode/base_dir.go
  internal/fs/inode/dir.go
  internal/fs/inode/dir_test.go
  internal/fs/kernel_list_cache_inifinite_ttl_test.go
  tools/integration_tests/kernel_list_cache/infinite_kernel_list_cache_test.go
Labels: execute-integration-tests

#2228 Pass correct enable-hns flag value while creating directory inode
  internal/fs/fs.go
  internal/fs/inode/explicit_dir.go
Labels: execute-integration-tests

#2229 Minor changes for stat cache for HNS
  internal/cache/metadata/stat_cache.go
  internal/storage/caching/fast_stat_bucket.go
  internal/storage/caching/fast_stat_bucket_test.go
Labels: execute-integration-tests

#2218 Set EnableEmptyManagedFolders if EnableHns is set
  cfg/rationalize.go
  cfg/rationalize_test.go
  cmd/config_rationalization_test.go
  cmd/legacy_param_mapper.go
  cmd/legacy_param_mapper_test.go
  cmd/root.go
Labels: execute-integration-tests

#2234 Callback getFolder in LookUpInode
  internal/fs/inode/dir.go
  internal/fs/inode/hns_dir_test.go
Labels: execute-integration-tests

#2243 Fix prefix bucket implementation for get folder
  internal/fs/inode/dir.go
  internal/fs/inode/hns_dir_test.go
  internal/gcsx/prefix_bucket.go
  internal/gcsx/prefix_bucket_test.go
  internal/storage/gcs/folder.go
  internal/storage/gcs/folder_test.go
Labels: execute-integration-tests

#2241 Fixing e2e test because of timeout in concurrent_list test
  tools/integration_tests/concurrent_operations/concurrent_listing_test.go
Labels: execute-integration-tests

#2237 Fixing error in listing for duplicate files
  internal/fs/handle/dir_handle.go
  internal/fs/handle/dir_handle_test.go
  internal/fs/inode/base_dir.go
  internal/fs/inode/dir.go
  internal/fs/inode/dir_test.go
  internal/fs/kernel_list_cache_test.go
  tools/integration_tests/concurrent_operations/concurrent_listing_test.go
  tools/integration_tests/local_file/read_dir_test.go
Labels: execute-integration-tests

#2242 adds and uses new method to insert objects and prefixes into stat cache
  internal/fs/inode/dir.go
  internal/storage/caching/fast_stat_bucket.go
  internal/storage/caching/fast_stat_bucket_test.go
Labels: execute-integration-tests

#2238 Create folder fs level integration
  internal/fs/inode/dir.go
  internal/fs/inode/hns_dir_test.go
  internal/gcsx/prefix_bucket.go
  internal/gcsx/prefix_bucket_test.go
  internal/storage/bucket_handle.go
  internal/storage/bucket_handle_test.go
  internal/storage/testify_mock_bucket.go
Labels: execute-integration-tests
