Repository GoogleCloudPlatform/gcsfuse, pull requests merged in 2024-11, with the labels that each got.

#2646 chore: upgrade go-stroage from 1.45.0 to 1.46.0
  go.mod
  go.sum
Labels: execute-perf-test, execute-integration-tests

#2650 Enabling read-stall-retry by default with best default
  cfg/config.go
  cfg/params.yaml
  cmd/config_validation_test.go
Labels: execute-perf-test, execute-integration-tests

#2653 Add enable-otel flag
  cfg/config.go
  cfg/params.yaml
  cmd/root_test.go
  cmd/testdata/metrics_config/empty.yml
  cmd/testdata/metrics_config/enable_otel_false.yml
  cmd/testdata/metrics_config/enable_otel_true.yml
Labels: execute-integration-tests

#2655 chore: enabling existing e2e test for gRPC
  perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/build.sh
  perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
  tools/integration_tests/list_large_dir/list_large_dir_test.go
Labels: execute-integration-tests

#2660 Dependabot merges
  go.mod
  go.sum
Labels: execute-perf-test, execute-integration-tests

#2627 Reducing list API payload
  internal/storage/bucket_handle.go
  internal/storage/fake/testing/bucket_tests.go
Labels: execute-integration-tests

#2657 replacing gcs.Object with gcs.MinObject in gcs.Listing
  internal/fs/inode/dir.go
  internal/fs/inode/hns_dir_test.go
  internal/gcsx/garbage_collect.go
  internal/gcsx/prefix_bucket.go
  internal/gcsx/prefix_bucket_test.go
  internal/storage/bucket_handle.go
  internal/storage/bucket_handle_test.go
  internal/storage/caching/fast_stat_bucket.go
  internal/storage/caching/fast_stat_bucket_test.go
  internal/storage/fake/bucket.go
  internal/storage/fake/testing/bucket_tests.go
  internal/storage/gcs/request.go
  internal/storage/storageutil/delete_all_objects.go
  internal/storage/storageutil/list_all.go
  internal/storage/storageutil/list_prefix.go
  internal/storage/storageutil/object_attrs.go
Labels: execute-integration-tests

#2671 enabling grpc for concurrent operations test
  tools/integration_tests/concurrent_operations/setup_test.go
Labels: automerge: exact, execute-integration-tests

#2683 Add warning logs for unsupported objects
  internal/fs/inode/dir.go
Labels: execute-integration-tests

#2688 chore: upgrading go-lang from 1.23.2 to 1.23.3
  Dockerfile
  go.mod
  perfmetrics/scripts/ml_tests/pytorch/run_model.sh
  perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
  perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
  perfmetrics/scripts/read_cache/setup.sh
  tools/cd_scripts/e2e_test.sh
  tools/containerize_gcsfuse_docker/Dockerfile
  tools/integration_tests/run_e2e_tests.sh
  tools/package_gcsfuse_docker/Dockerfile
Labels: execute-perf-test, execute-integration-tests, execute-package-build-tests

#2629 adding gcs call log for storage layout api
  internal/storage/bucket_handle.go
Labels: execute-integration-tests

#2689 chore: upgrading direct go-dependencies
  go.mod
  go.sum
Labels: execute-perf-test

#2690 chores: disable the read-stall-retry by default
  cfg/config.go
  cfg/params.yaml
  cmd/config_validation_test.go
Labels: execute-integration-tests

#2669 Upload handler implementation for buffered writes
  internal/block/block_pool.go
  internal/block/block_pool_test.go
  internal/bufferedwrites/upload_handler.go
  internal/bufferedwrites/upload_handler_test.go
  internal/storage/bucket_handle.go
  internal/storage/bucket_handle_test.go
  internal/storage/debug_bucket.go
  internal/storage/mock/mock_writer.go
Labels: minimal-file-buffering

#2667 Implement OTel Prometheus metrics exporter
  cfg/validate.go
  cfg/validate_test.go
  cmd/legacy_main.go
  go.mod
  go.sum
  internal/monitor/otelexporters.go
  internal/monitor/traceexporter.go
Labels: execute-integration-tests

#2670 Integrate UploadHandler in BufferedWriteHandler struct
  internal/bufferedwrites/buffered_write_handler.go
  internal/bufferedwrites/buffered_write_handler_test.go
  internal/fs/inode/file.go
Labels: minimal-file-buffering

#2698 Emit metrics to Cloud monitoring
  internal/monitor/otelexporters.go
Labels: execute-integration-tests

#2710 Add a private flag to throw clobbered error messages
  cfg/config.go
  cfg/params.yaml
  cmd/config_validation_test.go
  cmd/root_test.go
  cmd/testdata/valid_config.yaml
Labels: execute-integration-tests

#2713 Enabling grpc testing for relevant integration test packages
  tools/integration_tests/log_content/log_content_test.go
  tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go
  tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go
  tools/integration_tests/read_cache/disabled_cache_ttl_test.go
  tools/integration_tests/read_cache/job_chunk_test.go
  tools/integration_tests/read_cache/local_modification_test.go
  tools/integration_tests/read_cache/range_read_test.go
  tools/integration_tests/read_cache/read_only_test.go
  tools/integration_tests/read_cache/remount_test.go
  tools/integration_tests/read_cache/setup_test.go
  tools/integration_tests/read_cache/small_cache_ttl_test.go
  tools/integration_tests/read_large_files/read_large_files_test.go
  tools/integration_tests/run_e2e_tests.sh
Labels: execute-integration-tests

#2711 Upgrade deps
  go.mod
  go.sum
Labels: execute-perf-test, execute-integration-tests

#2716 Move version test to integration test.
  tools/build_gcsfuse/main_test.go
  tools/integration_tests/mounting/gcsfuse_test.go
Labels: execute-integration-tests

#2695 Handle error in uploader go routine
  internal/bufferedwrites/buffered_write_handler.go
  internal/bufferedwrites/buffered_write_handler_test.go
  internal/bufferedwrites/upload_handler.go
  internal/bufferedwrites/upload_handler_test.go
  internal/fs/inode/hns_dir_test.go
  internal/storage/mock/mock_writer.go
  internal/storage/mock/testify_mock_bucket.go
Labels: minimal-file-buffering

#2721 Unset the precondition flag until feature is complete
  cfg/config.go
  cfg/params.yaml
  cmd/config_validation_test.go
  cmd/root_test.go
  cmd/testdata/valid_config.yaml
Labels: execute-integration-tests

#2723 Fix Version test
  tools/integration_tests/mounting/gcsfuse_test.go
Labels: execute-integration-tests
