Repository GoogleCloudPlatform/gcsfuse, pull requests merged in 2025-08, with the labels that each got.

#3489 chores: Increase CI linux timeout to 25 minutes
  .github/workflows/ci.yml
Labels: remind-reviewers

#3625 feat(block-pool): adding tryGet similar to Get() but doesn't block execution when block-pool is full
  internal/block/block_pool.go
  internal/block/block_pool_test.go
Labels: remind-reviewers

#3618 feat(bufferedread): Integrate Buffered Reader with the filesystem
  internal/bufferedread/buffered_reader.go
  internal/bufferedread/buffered_reader_test.go
  internal/fs/fs.go
  internal/fs/handle/file.go
  internal/fs/handle/file_test.go
  internal/gcsx/read_manager/read_manager.go
  internal/gcsx/read_manager/read_manager_test.go
  internal/workerpool/static_worker_pool.go
  internal/workerpool/static_worker_pool_test.go
Labels: execute-integration-tests, remind-reviewers

#3627 style(debug_bkt): removing unnecessary back-slash from gcs-read log
  internal/storage/debug_bucket.go
Labels: execute-integration-tests, remind-reviewers

#3626 style(buffered-reader): Improving log and error message
  internal/block/prefetch_block.go
  internal/bufferedread/buffered_reader.go
  internal/bufferedread/buffered_reader_test.go
  internal/bufferedread/download_task.go
Labels: remind-reviewers

#3640 fix: Add flag check in accessing moveObject API for flat bucket
  internal/fs/fs.go
Labels: execute-integration-tests, remind-reviewers

#3643 feat(buffered-read): use blockPool's tryGet (unblocking) instead Get to
  internal/bufferedread/buffered_reader.go
Labels: remind-reviewers

#3619 feat(parallel random reads): Changes to enable parallel random read handling in gcs reader
  internal/fs/fs.go
  internal/fs/handle/file.go
  internal/fs/handle/file_test.go
  internal/gcsx/client_readers/gcs_reader.go
  internal/gcsx/client_readers/gcs_reader_test.go
  internal/gcsx/client_readers/multi_range_reader.go
  internal/gcsx/client_readers/multi_range_reader_test.go
  internal/gcsx/client_readers/range_reader.go
  internal/gcsx/client_readers/range_reader_test.go
  internal/gcsx/read_manager/read_manager_test.go
Labels: remind-reviewers

#3647 fix: install latest gcloud version in CD script tests
  tools/cd_scripts/e2e_test.sh
Labels: remind-reviewers

#3631 ci(micro bench): Spin GCE vm and run micro benchmark instead of on kokoro machine
  perfmetrics/scripts/build_and_install_gcsfuse.sh
  perfmetrics/scripts/continuous_test/gcp_ubuntu/micro_benchmarks/build.sh
  perfmetrics/scripts/continuous_test/gcp_ubuntu/micro_benchmarks/continuous.cfg
  perfmetrics/scripts/micro_benchmarks/run_microbenchmark.sh
Labels: remind-reviewers

#3652 fix(e2e script): add logs if bucket creation fails in e2e script
  tools/integration_tests/improved_run_e2e_tests.sh
Labels: remind-reviewers

#3629 test(buffered-read): adding log parser utility required for buffered-read e2e test
  tools/integration_tests/util/log_parser/json_parser/read_logs/buffered_read_log_parser.go
  tools/integration_tests/util/log_parser/json_parser/read_logs/buffered_read_log_parser_test.go
  tools/integration_tests/util/log_parser/json_parser/read_logs/helpers.go
  tools/integration_tests/util/log_parser/json_parser/read_logs/json_read_log_parser_test.go
  tools/integration_tests/util/log_parser/json_parser/read_logs/structure.go
Labels: remind-reviewers

#3609 ci: save failure gcsfuse logs and add more useful debug logs for e2e benchmarking package
  tools/integration_tests/benchmarking/benchmark_delete_test.go
  tools/integration_tests/benchmarking/benchmark_rename_test.go
  tools/integration_tests/benchmarking/benchmark_stat_test.go
  tools/integration_tests/benchmarking/setup_test.go
Labels: remind-reviewers

#3651 chore(metrics): sampled logging for undeclared metric attributes
  optimizedmetrics/otel_metrics.go
  tools/metrics-gen/main.go
  tools/metrics-gen/otel_metrics.tpl
Labels: remind-reviewers

#3654 docs: Add information regarding ESTALE error in troubleshooting guide
  docs/troubleshooting.md
Labels: remind-reviewers

#3656 chore(metrics): disable exemplar filter for metrics
  internal/monitor/otelexporters.go
Labels: execute-integration-tests, execute-integration-tests-on-zb, remind-reviewers

#3650 test: Move proxy server out of integration tests folder
  tools/integration_tests/emulator_tests/configs/config.yaml
  tools/integration_tests/emulator_tests/configs/empty_gcs_file_2nd_chunk_upload_returns412.yaml
  tools/integration_tests/emulator_tests/configs/local_file_2nd_chunk_upload_returns412.yaml
  tools/integration_tests/emulator_tests/configs/read_stall_5s.yaml
  tools/integration_tests/emulator_tests/configs/write_stall_40s.yaml
  tools/integration_tests/emulator_tests/configs/write_stall_twice_40s.yaml
  tools/integration_tests/emulator_tests/read_stall/read_stall_test.go
  tools/integration_tests/emulator_tests/streaming_writes_failure/empty_gcs_file_failure_test.go
  tools/integration_tests/emulator_tests/streaming_writes_failure/new_local_file_failure_test.go
  tools/integration_tests/emulator_tests/util/test_helper.go
  tools/integration_tests/emulator_tests/write_stall/writes_stall_on_sync_test.go
  tools/proxy_server/config.go
  tools/proxy_server/config_test.go
  tools/proxy_server/emulator.go
  tools/proxy_server/emulator_test.go
  tools/proxy_server/main.go
  tools/proxy_server/main_test.go
  tools/proxy_server/operation_manager.go
  tools/proxy_server/operation_manager_test.go
  tools/proxy_server/request_mapper.go
  tools/proxy_server/request_mappper_test.go
Labels: execute-integration-tests, remind-reviewers

#3662 fix: Kokoro tests failure
  perfmetrics/scripts/build_and_install_gcsfuse.sh
Labels: execute-package-build-tests, remind-reviewers

#3666 fix(metrics): Prevent panic from unrecognized histogram attributes
  metrics/otel_metrics.go
  tools/metrics-gen/main.go
Labels: remind-reviewers

#3671 chore(metrics): add missing metric attribute values
  metrics/metrics.yaml
  metrics/otel_metrics.go
  metrics/otel_metrics_test.go
Labels: remind-reviewers

#3669 refactor: explicit_dir test package migration [GKE-GCSFuse Test migration]
  tools/integration_tests/explicit_dir/explicit_dir_test.go
  tools/integration_tests/test_config.yaml
  tools/integration_tests/util/mounting/persistent_mounting/perisistent_mounting.go
  tools/integration_tests/util/mounting/static_mounting/static_mounting.go
  tools/integration_tests/util/setup/implicit_and_explicit_dir_setup/implicit_and_explicit_dir_setup.go
  tools/integration_tests/util/setup/setup.go
  tools/integration_tests/util/test_suite/config.go
Labels: remind-reviewers

#3610 feat(Migrate auth TPC): Make default value of flag true
  cfg/config.go
  cfg/params.yaml
  cmd/root_test.go
  tools/integration_tests/util/mounting/static_mounting/static_mounting.go
Labels: remind-reviewers

#3677 fix(Buffered read): Make buffered read path thread safe
  internal/bufferedread/buffered_reader.go
  internal/bufferedread/buffered_reader_test.go
  internal/fs/handle/file_test.go
Labels: remind-reviewers

#3685 test(bufferedread): Add setup and helper methods for Buffered Read integration tests
  internal/bufferedread/buffered_reader.go
  internal/util/util.go
  tools/cd_scripts/e2e_test.sh
  tools/integration_tests/buffered_read/helpers_test.go
  tools/integration_tests/buffered_read/sequential_read_test.go
  tools/integration_tests/buffered_read/setup_test.go
  tools/integration_tests/improved_run_e2e_tests.sh
  tools/integration_tests/run_e2e_tests.sh
  tools/integration_tests/util/log_parser/json_parser/read_logs/buffered_read_log_parser.go
  tools/integration_tests/util/log_parser/json_parser/read_logs/buffered_read_log_parser_test.go
  tools/integration_tests/util/log_parser/json_parser/read_logs/structure.go
  tools/integration_tests/util/operations/file_operations.go
Labels: execute-integration-tests, remind-reviewers

#3691 fix(bash installation): use latest bash 5.3 and improve logging in case of error.
  perfmetrics/scripts/install_bash.sh
  perfmetrics/scripts/presubmit_test/pr_perf_test/build.sh
Labels: execute-integration-tests-on-zb, remind-reviewers

#3693 feat(bufferedread): Add integration tests for fallback mechanism in buffered reader
  internal/bufferedread/buffered_reader_test.go
  tools/integration_tests/buffered_read/fallback_test.go
  tools/integration_tests/buffered_read/helpers_test.go
  tools/integration_tests/buffered_read/setup_test.go
  tools/integration_tests/util/log_parser/json_parser/read_logs/buffered_read_log_parser.go
Labels: execute-integration-tests, remind-reviewers

#3708 refactor: list large dir test package migration [GKE-GCSFuse Test migration]
  tools/integration_tests/list_large_dir/list_large_dir_test.go
  tools/integration_tests/test_config.yaml
  tools/integration_tests/util/setup/setup.go
Labels: remind-reviewers

#3710 chore(deps): Upgrade go sdk dependency to storage@v1.56.1
  go.mod
  go.sum
Labels: execute-perf-test, execute-integration-tests

#3712 revert(enable-write-stall): enable write stall in streaming writes
  internal/storage/bucket_handle.go
  tools/integration_tests/emulator_tests/write_stall/writes_stall_on_sync_test.go
Labels: execute-integration-tests, execute-integration-tests-on-zb, remind-reviewers

#3719 fix(review reminder): fix auto reminder issue when PR is raised from fork gcsfuse.
  .github/workflows/auto-pr-reminder.yml
Labels: remind-reviewers

#3714 fix: re-use read handle from previous read.
  internal/storage/bucket_handle.go
  internal/storage/debug_bucket.go
Labels: execute-integration-tests-on-zb

#3726 test: Add buffered read integration tests in mounted directory script
  tools/integration_tests/run_tests_mounted_directory.sh
Labels: remind-reviewers

#3733 feat(bufferedread): Modify default mount config for buffered read as per experiments
  cfg/config.go
  cfg/params.yaml
  cmd/config_validation_test.go
  cmd/root_test.go
  cmd/testdata/valid_config.yaml
Labels: remind-reviewers

#3744 style(control client): Remove unused method parameter
  internal/storage/storage_handle.go
  internal/storage/storageutil/control_client.go
  internal/storage/storageutil/control_client_test.go
Labels: remind-reviewers

#3737 feat(bufferedread): Enabling both file cache and buffered read should disable buffered read
  cfg/rationalize.go
  cfg/rationalize_test.go
Labels: remind-reviewers

#3746 fix(log level): Downgrade info log to trace.
  internal/gcsx/inactive_timeout_reader.go
Labels: execute-integration-tests, remind-reviewers

#3750 feat(Buffered Read): Make flag for Random seek count
  cfg/config.go
  cfg/params.yaml
  cmd/config_validation_test.go
  cmd/testdata/valid_config.yaml
  internal/bufferedread/buffered_reader.go
  internal/bufferedread/buffered_reader_test.go
  internal/gcsx/read_manager/read_manager.go
Labels: remind-reviewers

#3753 refactor: update parsing the yaml file & Zonal bucket case handling [GKE-GCSFuse Test migration]
  tools/integration_tests/explicit_dir/explicit_dir_test.go
  tools/integration_tests/implicit_dir/implicit_dir_test.go
  tools/integration_tests/list_large_dir/list_large_dir_test.go
Labels: remind-reviewers

#3755 fix: Hide flag create-empty-file on gcsfuse --help
  cfg/config.go
  cfg/params.yaml
Labels: execute-integration-tests, remind-reviewers

#3760 feat(bufferedread): Update default value of readGlobalMaxBlocks to 40
  cfg/config.go
  cfg/params.yaml
  cmd/config_validation_test.go
  cmd/root_test.go
  cmd/testdata/valid_config.yaml
Labels: remind-reviewers

#3759 refactor: readonly test package migration [GKE-GCSFuse Test migration]
  tools/integration_tests/explicit_dir/explicit_dir_test.go
  tools/integration_tests/gzip/gzip_test.go
  tools/integration_tests/implicit_dir/implicit_dir_test.go
  tools/integration_tests/list_large_dir/list_large_dir_test.go
  tools/integration_tests/readonly/readonly_test.go
  tools/integration_tests/test_config.yaml
  tools/integration_tests/util/creds_tests/creds.go
  tools/integration_tests/util/setup/setup.go
  tools/integration_tests/write_large_files/write_large_files_test.go
Labels: remind-reviewers

#3763 ci: Preserve gcsfuse log file for e2e package concurrent_operations on failure
  tools/integration_tests/concurrent_operations/setup_test.go
Labels: remind-reviewers
