Repository GoogleCloudPlatform/gcsfuse, pull requests merged in 2025-07, with the labels that each got.

#3401 [read-unfinalized-object] [part1] Relax file-cache checks for unfinalized objects
  internal/cache/file/cache_handle.go
  internal/cache/file/cache_handler.go
  internal/gcsx/file_cache_reader_test.go
  internal/gcsx/random_reader_test.go
  internal/gcsx/read_manager/read_manager_test.go
  internal/storage/gcs/object.go
  internal/storage/gcs/object_test.go
Labels: remind-reviewers

#3439 Add metric for retries caused by gcs errors.
  cmd/legacy_main.go
  cmd/legacy_main_test.go
  common/noop_metrics.go
  common/otel_metrics.go
  common/telemetry.go
  internal/storage/storage_handle.go
  internal/storage/storageutil/client.go
  internal/storage/storageutil/custom_retry.go
  internal/storage/storageutil/custom_retry_test.go
Labels: execute-integration-tests

#3467 Update Jacobsa FUSE version and add initial support for ReadDirPlus
  go.mod
  go.sum
  internal/fs/fs.go
  internal/fs/wrappers/error_mapping.go
  internal/fs/wrappers/monitoring.go
  internal/fs/wrappers/tracing.go
  internal/fs/wrappers/tracing_test.go
Labels: execute-perf-test, execute-integration-tests

#3474 Make PR review reminder default with Auto applying label on new/open/repopened PR(s).
  .github/workflows/auto-pr-reminder.yml
  .github/workflows/pr-reminder.yml
Labels: remind-reviewers

#3475 Block Pool: Release Block Flow Improvement for Buffered Write
  internal/block/block_pool.go
  internal/bufferedwrites/buffered_write_handler.go
  internal/bufferedwrites/upload_handler.go
  internal/bufferedwrites/upload_handler_test.go
Labels: remind-reviewers

#3479 Block: Adding ReadAt method in block interface and memoryBlock
  internal/block/block.go
  internal/block/block_test.go
Labels: remind-reviewers

#3405 [read-unfinalized-object] [part2] Enable read of unfinalized objects while being written via streaming
  internal/fs/fs.go
  internal/fs/inode/file.go
  internal/fs/inode/file_streaming_writes_test.go
  internal/fs/inode/file_test.go
  tools/integration_tests/streaming_writes/common_streaming_writes_suite_test.go
  tools/integration_tests/unfinalized_object/unfinalized_read_test.go
Labels: remind-reviewers

#3480 Block: Adding Getter/Setter for the AbsStartOffset in the block
  internal/block/block.go
  internal/block/block_test.go
Labels: remind-reviewers

#3478 Add boolean clobberedCheck parameter to Attributes method of Inode interface
  internal/fs/fs.go
  internal/fs/inode/base_dir.go
  internal/fs/inode/base_dir_test.go
  internal/fs/inode/dir.go
  internal/fs/inode/dir_test.go
  internal/fs/inode/file.go
  internal/fs/inode/file_streaming_writes_test.go
  internal/fs/inode/file_test.go
  internal/fs/inode/inode.go
  internal/fs/inode/symlink.go
  internal/fs/inode/symlink_test.go
Labels: remind-reviewers

#3469 Add ReadEntryCores method to DirInode interface
  internal/fs/inode/base_dir.go
  internal/fs/inode/base_dir_test.go
  internal/fs/inode/dir.go
  internal/fs/inode/dir_test.go
Labels: execute-perf-test, execute-integration-tests

#3486 [Process Improvement] Standardize PR titles
  .github/pull_request_template.md
  .github/workflows/pr-title-check.yml
Labels: remind-reviewers

#3493 docs: update troubleshooting doc for exit 1 error
  docs/troubleshooting.md
Labels: remind-reviewers

#3496 fix(bash installation): Fix bash installation script to install gcc/make dependencies before installing bash.
  perfmetrics/scripts/install_bash.sh
Labels: execute-integration-tests, execute-integration-tests-on-zb, remind-reviewers

#3484 feat(buffered-read): implement download task for worker pool
  internal/bufferedread/download_task.go
  internal/bufferedread/download_task_test.go
Labels: remind-reviewers

#3506 ci: Upgrade to python311 in micro benchmark script
  perfmetrics/scripts/continuous_test/gcp_ubuntu/micro_benchmarks/build.sh
  perfmetrics/scripts/upgrade_python3.sh
Labels: remind-reviewers

#3490 Dir Handle changes to support Readdirplus operation
  internal/fs/handle/dir_handle.go
  internal/fs/handle/dir_handle_test.go
  internal/fs/inode/dir.go
Labels: execute-perf-test, execute-integration-tests, remind-reviewers

#3507 fix(review reminder): exclude dependabot from review reminders.
  .github/workflows/auto-pr-reminder.yml
Labels: remind-reviewers

#3516 ci: Fix kokoro failure in micro benchmark script
  perfmetrics/scripts/continuous_test/gcp_ubuntu/micro_benchmarks/build.sh
Labels: remind-reviewers

#3518 ci: Add missing dependency for micro benchmarks failing on kokoro machine
  perfmetrics/scripts/continuous_test/gcp_ubuntu/micro_benchmarks/build.sh
  perfmetrics/scripts/micro_benchmarks/requirements.txt
Labels: remind-reviewers

#3505 docs(troubleshooting): Update troubleshooting doc for unsupported objects
  docs/troubleshooting.md
Labels: remind-reviewers

#3520 refactor(formatting): Disable goimports in Makefile
  Makefile
Labels: remind-reviewers

#3502 feat(buffered-read): passing error for failed state via notification channel
  internal/block/block.go
  internal/block/block_test.go
  internal/bufferedread/download_task.go
  internal/bufferedread/download_task_test.go
Labels: remind-reviewers

#3527 feat(Readdirplus): Integrate readdirplus with flag
  cmd/mount.go
  cmd/mount_test.go
Labels: remind-reviewers

#3402 feat(Random Reader Refactoring): Enable new reader implementation by default
  cfg/config.go
  cfg/params.yaml
  cmd/root_test.go
  internal/fs/fs_test.go
  internal/gcsx/file_cache_reader.go
Labels: execute-perf-test, execute-integration-tests, execute-integration-tests-on-zb, random-reader-refactoring, remind-reviewers

#3510 feat(Readdirplus): Implement ReadDirPlus operation
  internal/fs/fs.go
  internal/fs/read_dir_plus_test.go
Labels: execute-perf-test, execute-integration-tests, remind-reviewers

#3531 chore(deps): Update jacobsa fuse version
  go.mod
  go.sum
Labels: execute-perf-test, execute-integration-tests

#3529 feat(entry-timeout): Set EntryExpiration for dentry caching
  internal/fs/fs.go
  internal/fs/read_dir_plus_test.go
Labels: remind-reviewers

#3540 fix: improve logging while unmount external mount
  cmd/legacy_main.go
  go.mod
  go.sum
Labels: remind-reviewers

#3473 ci(read unfinalized objects): Add new e2e tests for reads of unfinalized objects while being appended
  tools/integration_tests/improved_run_e2e_tests.sh
  tools/integration_tests/rapid_appends/rapid_appends_test.go
  tools/integration_tests/rapid_appends/setup_test.go
  tools/integration_tests/unfinalized_object/unfinalized_object_operations_test.go
  tools/integration_tests/util/client/gcs_helper.go
  tools/integration_tests/util/operations/file_operations.go
Labels: execute-integration-tests-on-zb, remind-reviewers

#3533 feat(Readdirplus): Add e2e test for Readdirplus
  tools/integration_tests/improved_run_e2e_tests.sh
  tools/integration_tests/readdirplus/readdirplus_with_dentry_cache_test.go
  tools/integration_tests/readdirplus/readdirplus_without_dentry_cache_test.go
  tools/integration_tests/readdirplus/setup_test.go
  tools/integration_tests/run_e2e_tests.sh
  tools/integration_tests/run_tests_mounted_directory.sh
Labels: execute-perf-test, execute-integration-tests, remind-reviewers

#3528 ci(debugging): Save gcsfuse logs for failed mount_timeout package
  tools/integration_tests/mount_timeout/gcsfuse_mount_timeout_test.go
Labels: execute-integration-tests, execute-integration-tests-on-zb, remind-reviewers

#3551 fix(caching): Invalidate fast stat cache on NotFoundError
  internal/storage/caching/fast_stat_bucket.go
  internal/storage/caching/fast_stat_bucket_test.go
Labels: remind-reviewers

#3534 chore(ci): Don't run go specific test if PR doesn't contain any related file
  .github/workflows/ci.yml
Labels: remind-reviewers

#3558 ci: moving path filters check at job.steps level
  .github/workflows/ci.yml
Labels: remind-reviewers

#3554 chore(ci.yml): Don't run linter on post-submit runs
  .github/workflows/ci.yml
Labels: remind-reviewers

#3549 chore(PR Template): Update pull_request_template.md
  .github/pull_request_template.md
Labels: remind-reviewers

#3555 feat(Notifier): Use notifier to invalidate stale dentry cache on clobber
  cmd/mount.go
  common/util.go
  common/util_test.go
  internal/fs/fs.go
  internal/fs/inode/name.go
  internal/fs/inode/name_test.go
  internal/fs/notifier_test.go
  internal/fs/server.go
Labels: remind-reviewers

#3552 feat(bufferedread): Add initial structs for buffered reader
  internal/bufferedread/buffered_reader.go
  internal/bufferedread/buffered_reader_test.go
Labels: remind-reviewers

#3569 docs(semantics): Supporting symlinks to external paths
  docs/semantics.md
Labels: remind-reviewers

#3544 feat(Migrate Auth TPC): Function for creating credentials/tokenSource/UniverseDomain and add option for client
  go.mod
  internal/storage/storageutil/auth_client_option.go
  internal/storage/storageutil/auth_client_option_test.go
  internal/storage/storageutil/testdata/key.json
Labels: remind-reviewers

#3565 refactor(parallel random reads): Changes to start using atomic variables for shared state in read path
  internal/cache/file/downloader/job.go
  internal/cache/file/downloader/parallel_downloads_job.go
  internal/gcsx/client_readers/gcs_reader.go
  internal/gcsx/client_readers/gcs_reader_test.go
  internal/gcsx/client_readers/range_reader.go
  internal/gcsx/client_readers/range_reader_test.go
  internal/gcsx/file_cache_reader.go
  internal/gcsx/random_reader.go
  internal/gcsx/random_reader_stretchr_test.go
  internal/gcsx/random_reader_test.go
  metrics/constants.go
Labels: remind-reviewers

#3575 fix: rename gemini config yaml
  .gemini/config.yaml
Labels: remind-reviewers

#3522 test(rapid appends): appends from a handle after takeover from another client must fail
  tools/integration_tests/rapid_appends/appends_test.go
  tools/integration_tests/rapid_appends/setup_test.go
Labels: execute-integration-tests-on-zb, remind-reviewers

#3576 style: removing unused code part -1
  cmd/legacy_main.go
  internal/fs/foreign_modifications_test.go
  internal/fs/fs.go
  internal/fs/fs_test.go
  internal/fs/handle/dir_handle_test.go
  internal/fs/local_modifications_test.go
  internal/fs/read_cache_test.go
  internal/storage/bucket_handle.go
  internal/storage/bucket_handle_test.go
  internal/storage/fake/testing/bucket_tests.go
  internal/storage/storageutil/client_test.go
  internal/util/sizeof.go
  tools/integration_tests/gzip/gzip_test.go
  tools/integration_tests/gzip/read_gzip_test.go
  tools/integration_tests/kernel_list_cache/disabled_kernel_list_cache_test.go
  tools/integration_tests/kernel_list_cache/finite_kernel_list_cache_test.go
  tools/integration_tests/kernel_list_cache/infinite_kernel_list_cache_delete_dir_test.go
  tools/integration_tests/kernel_list_cache/infinite_kernel_list_cache_test.go
  tools/integration_tests/kernel_list_cache/setup_test.go
  tools/integration_tests/read_cache/helpers_test.go
  tools/integration_tests/read_cache/remount_test.go
  tools/integration_tests/readdirplus/readdirplus_with_dentry_cache_test.go
  tools/integration_tests/readdirplus/readdirplus_without_dentry_cache_test.go
  tools/integration_tests/readdirplus/setup_test.go
  tools/integration_tests/util/mounting/persistent_mounting/perisistent_mounting.go
Labels: execute-integration-tests, remind-reviewers

#3476 Block: Making block interface a reader
  internal/block/block.go
  internal/block/block_pool_test.go
  internal/block/block_test.go
  internal/block/prefetch_block_test.go
  internal/bufferedwrites/upload_handler.go
Labels: execute-integration-tests, remind-reviewers

#3562 feat(dentry cache): Add integration tests for dentry cache
  internal/fs/wrappers/error_mapping.go
  tools/cd_scripts/e2e_test.sh
  tools/integration_tests/dentry_cache/notifier_test.go
  tools/integration_tests/dentry_cache/setup_test.go
  tools/integration_tests/dentry_cache/stat_test.go
  tools/integration_tests/improved_run_e2e_tests.sh
  tools/integration_tests/run_e2e_tests.sh
  tools/integration_tests/run_tests_mounted_directory.sh
Labels: execute-integration-tests, remind-reviewers

#3538 test(rapid appends): Appends to finalized object is not visible on GCS till Close()
  tools/integration_tests/rapid_appends/appends_test.go
Labels: execute-integration-tests-on-zb

#3568 ci: Correction from Mbps to MB/s
  perfmetrics/scripts/micro_benchmarks/helper.py
  perfmetrics/scripts/micro_benchmarks/read_single_thread.py
  perfmetrics/scripts/micro_benchmarks/write_single_thread.py
Labels: remind-reviewers

#3545 test(rapid appends): appends with concurrent file handles must be real time
  tools/integration_tests/rapid_appends/appends_test.go
  tools/integration_tests/rapid_appends/setup_test.go
Labels: execute-integration-tests-on-zb

#3579 style: removing unused code - part2
  internal/fs/handle/dir_handle_test.go
  internal/fs/handle/file_test.go
  internal/fs/inode/dir_test.go
  internal/fs/inode/file_streaming_writes_test.go
  internal/fs/stale_file_handle_common_test.go
  internal/fs/stale_file_handle_streaming_writes_common_test.go
  internal/fs/stale_file_handle_streaming_writes_local_file_test.go
  internal/fs/stale_file_handle_streaming_writes_synced_file_test.go
  internal/fs/stale_file_handle_synced_file_test.go
  internal/gcsx/file_cache_reader_test.go
  internal/gcsx/inactive_timeout_reader_test.go
  internal/storage/caching/integration_test.go
  tools/integration_tests/read_cache/cache_file_for_exclude_regex_test.go
  tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go
  tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go
  tools/integration_tests/read_cache/disabled_cache_ttl_test.go
  tools/integration_tests/read_cache/helpers_test.go
  tools/integration_tests/read_cache/job_chunk_test.go
  tools/integration_tests/read_cache/local_modification_test.go
  tools/integration_tests/read_cache/range_read_test.go
  tools/integration_tests/read_cache/read_only_test.go
  tools/integration_tests/read_cache/remount_test.go
  tools/integration_tests/read_cache/setup_test.go
  tools/integration_tests/read_cache/small_cache_ttl_test.go
  tools/package_gcsfuse/build.go
  tools/package_gcsfuse/main.go
  tools/package_gcsfuse/package.go
Labels: execute-integration-tests, remind-reviewers

#3580 feat(bufferedread): Add freshStart and prefetch methods to Buffered Reader
  internal/bufferedread/buffered_reader.go
  internal/bufferedread/buffered_reader_test.go
Labels: remind-reviewers

#3597 refactor: removing cancelled block state
  internal/block/prefetch_block.go
  internal/block/prefetch_block_test.go
  internal/bufferedread/buffered_reader_test.go
  internal/bufferedread/download_task.go
  internal/bufferedread/download_task_test.go
Labels: remind-reviewers

#3567 chore(deps): Upgrade direct dependencies
  go.mod
  go.sum
Labels: execute-perf-test, execute-integration-tests, remind-reviewers

#3598 feat(bufferedread): adding mount config to control buffered-read feature
  cfg/config.go
  cfg/params.yaml
  cfg/validate.go
  cfg/validate_test.go
  cmd/config_validation_test.go
  cmd/root_test.go
  cmd/testdata/valid_config.yaml
Labels: remind-reviewers

#3605 ci: fail fast in utility CreateDirectoryWithNFiles
  tools/integration_tests/util/operations/dir_operations.go
Labels: execute-integration-tests, execute-integration-tests-on-zb, remind-reviewers

#3606 fix: fail gcsfuse e2e tests if testBucket argument is improper
  tools/integration_tests/util/setup/setup.go
Labels: execute-integration-tests-on-zb, remind-reviewers

#3586 style: remove unused code - part3 and adding lint check
  .github/workflows/ci.yml
  cfg/optimize.go
  cfg/optimize_test.go
  cmd/root.go
Labels: execute-integration-tests, remind-reviewers

#3608 test(rapid appends): test size visible to kernel on appends
  tools/integration_tests/rapid_appends/appends_test.go
Labels: execute-integration-tests-on-zb, remind-reviewers

#3602 feat(bufferedread): Implement ReadAt method of Buffered Reader
  internal/block/prefetch_block.go
  internal/bufferedread/buffered_reader.go
  internal/bufferedread/buffered_reader_test.go
  internal/bufferedread/download_task.go
Labels: remind-reviewers

#3612 ci: fix only-dir testing in implicit_dir test package
  tools/integration_tests/implicit_dir/implicit_dir_test.go
  tools/integration_tests/util/client/storage_client.go
  tools/integration_tests/util/setup/implicit_and_explicit_dir_setup/implicit_and_explicit_dir_setup.go
  tools/integration_tests/util/setup/setup.go
Labels: execute-integration-tests-on-zb, remind-reviewers

#3614 perf(metrics): Code-generate tests for metrics.
  optimizedmetrics/otel_metrics.go
  optimizedmetrics/otel_metrics_test.go
  tools/metrics-gen/main.go
  tools/metrics-gen/otel_metrics.tpl
  tools/metrics-gen/otel_metrics_test.tpl
Labels: remind-reviewers
