Repository GoogleCloudPlatform/gcsfuse, pull requests merged in 2025-09, with the labels that each got.

#3768 fix(unmount): Fixing false unmount success bug
  go.mod
  go.sum
Labels: execute-perf-test, execute-integration-tests

#3770 ci(debug e2e failure): Enable trace logs in e2e package mount-timeout
  tools/integration_tests/mount_timeout/gcsfuse_mount_timeout_test.go
Labels: execute-integration-tests, remind-reviewers

#3740 chore(dep upgrade): Dependency upgrades
  go.mod
  go.sum
Labels: execute-perf-test, execute-integration-tests, remind-reviewers

#3772 refactor: migrate packages to use stretchr testify and clean up test_setup package
  tools/integration_tests/concurrent_operations/concurrent_listing_test.go
  tools/integration_tests/concurrent_operations/concurrent_read_test.go
  tools/integration_tests/dentry_cache/delete_operation_test.go
  tools/integration_tests/dentry_cache/notifier_test.go
  tools/integration_tests/dentry_cache/stat_test.go
  tools/integration_tests/emulator_tests/write_stall/writes_stall_on_sync_test.go
  tools/integration_tests/gzip/write_gzip_test.go
  tools/integration_tests/inactive_stream_timeout/with_timeout_test.go
  tools/integration_tests/inactive_stream_timeout/without_timeout_test.go
  tools/integration_tests/interrupt/git_clone_test.go
  tools/integration_tests/kernel_list_cache/disabled_kernel_list_cache_test.go
  tools/integration_tests/kernel_list_cache/finite_kernel_list_cache_test.go
  tools/integration_tests/kernel_list_cache/infinite_kernel_list_cache_delete_dir_test.go
  tools/integration_tests/kernel_list_cache/infinite_kernel_list_cache_test.go
  tools/integration_tests/managed_folders/admin_permissions_test.go
  tools/integration_tests/managed_folders/list_empty_managed_folders_test.go
  tools/integration_tests/managed_folders/view_permissions_test.go
  tools/integration_tests/negative_stat_cache/disabled_negative_stat_cache_test.go
  tools/integration_tests/negative_stat_cache/finite_int_negative_stat_cache_test.go
  tools/integration_tests/negative_stat_cache/infinite_negative_stat_cache_test.go
  tools/integration_tests/read_cache/cache_file_for_exclude_regex_test.go
  tools/integration_tests/read_cache/cache_file_for_range_read_false_test.go
  tools/integration_tests/read_cache/cache_file_for_range_read_true_test.go
  tools/integration_tests/read_cache/disabled_cache_ttl_test.go
  tools/integration_tests/read_cache/job_chunk_test.go
  tools/integration_tests/read_cache/local_modification_test.go
  tools/integration_tests/read_cache/range_read_test.go
  tools/integration_tests/read_cache/read_only_test.go
  tools/integration_tests/read_cache/remount_test.go
  tools/integration_tests/read_cache/small_cache_ttl_test.go
  tools/integration_tests/readdirplus/readdirplus_with_dentry_cache_test.go
  tools/integration_tests/readdirplus/readdirplus_without_dentry_cache_test.go
  tools/integration_tests/readonly/readonly_test.go
  tools/integration_tests/readonly_creds/failure_during_file_sync_test.go
  tools/integration_tests/util/test_setup/test_setup.go
  tools/integration_tests/util/test_setup/test_setup_test.go
Labels: execute-integration-tests, remind-reviewers

#3773 fix(config): Use BlockSizeMb value in form of MB instead of converting it to bytes during rationalization.
  cfg/rationalize.go
  cfg/rationalize_test.go
  cmd/config_validation_test.go
  cmd/root_test.go
  internal/fs/inode/file.go
  internal/fs/inode/file_test.go
  internal/fs/stale_file_handle_streaming_writes_common_test.go
  internal/fs/streaming_writes_empty_gcs_object_test.go
  internal/fs/streaming_writes_local_file_test.go
Labels: execute-integration-tests, execute-integration-tests-on-zb, remind-reviewers

#3745 refactor: read large files test package migration [GKE-GCSFuse Test migration]
  tools/integration_tests/read_large_files/read_large_files_test.go
  tools/integration_tests/test_config.yaml
  tools/integration_tests/util/setup/setup.go
Labels: remind-reviewers

#3778 revert: Revert "feat(Migrate auth TPC): Make default value of flag true (#3610)"
  cmd/root_test.go
  tools/integration_tests/util/mounting/static_mounting/static_mounting.go
Labels: execute-integration-tests, remind-reviewers

#3781 fix(e2e random error): Retry on failed to resolve host github.com
  tools/integration_tests/interrupt/git_clone_test.go
Labels: execute-integration-tests, remind-reviewers

#3794 feat(bufferedread): Reduce the channel size in workerpool to 2 times Global Max Read Blocks
  internal/bufferedread/buffered_reader_test.go
  internal/gcsx/read_manager/read_manager_test.go
  internal/workerpool/static_worker_pool.go
  internal/workerpool/static_worker_pool_test.go
Labels: execute-integration-tests, remind-reviewers

#3366 feat: support rename of local file
  internal/fs/fs.go
  internal/fs/local_file_test.go
  internal/fs/stale_file_handle_synced_file_test.go
  tools/integration_tests/local_file/create_file_test.go
  tools/integration_tests/local_file/edit_file_test.go
  tools/integration_tests/local_file/local_file_helper.go
  tools/integration_tests/local_file/local_file_suite.go
  tools/integration_tests/local_file/read_dir_test.go
  tools/integration_tests/local_file/read_file_test.go
  tools/integration_tests/local_file/remove_dir_test.go
  tools/integration_tests/local_file/rename_test.go
  tools/integration_tests/local_file/setup_test.go
  tools/integration_tests/local_file/stat_file_test.go
  tools/integration_tests/local_file/sym_link_test.go
  tools/integration_tests/local_file/unlinked_file_test.go
  tools/integration_tests/local_file/write_file_test.go
  tools/integration_tests/stale_handle/stale_file_handle_common_test.go
  tools/integration_tests/streaming_writes/local_file_test.go
  tools/integration_tests/util/client/gcs_helper.go
  tools/integration_tests/util/operations/file_operations.go
  tools/integration_tests/util/operations/validation_helper.go
Labels: execute-integration-tests, remind-reviewers

#3811 ci(kokoro): copy sponge logs to artifacts to gcsfuse kokoro bucket
  perfmetrics/scripts/continuous_test/gcp_ubuntu/continuous.cfg
  perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/checkpoint-tests.cfg
  perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/e2e-tests-master-zb.cfg
  perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/e2e-tests-master.cfg
  perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/e2e-tests-release.cfg
  perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/e2e-tests-tpc.cfg
Labels: remind-reviewers

#3812 fix(ci build): Fix script arguments to be passed for improved_e2e_test from ci build
  perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/build.sh
  perfmetrics/scripts/continuous_test/gcp_ubuntu/e2e_tests/tpc_build.sh
Labels: remind-reviewers

#3815 fix: bucket name while identifying Bucket Type for only-dir mount tests
  tools/integration_tests/util/setup/setup.go
Labels: remind-reviewers

#3795 feat: Retry for short reads & MRD Read Handle Support
  internal/cache/util/util.go
  internal/gcsx/client_readers/gcs_reader.go
  internal/gcsx/client_readers/gcs_reader_test.go
  internal/gcsx/client_readers/multi_range_reader.go
  internal/gcsx/client_readers/multi_range_reader_test.go
  internal/gcsx/client_readers/range_reader.go
  internal/gcsx/client_readers/range_reader_test.go
  internal/gcsx/multi_range_downloader_wrapper.go
  internal/gcsx/multi_range_downloader_wrapper_test.go
  internal/gcsx/random_reader.go
  internal/gcsx/read_manager/read_manager_test.go
  internal/gcsx/reader.go
  internal/storage/bucket_handle.go
  internal/storage/debug_bucket.go
  internal/storage/fake/fake_multi_range_downloader.go
  internal/storage/gcs/multi_range_downloader.go
  internal/storage/gcs/request.go
Labels: remind-reviewers

#3822 test: Fixing errors in concurrent listing package
  tools/integration_tests/concurrent_operations/concurrent_listing_test.go
Labels: remind-reviewers

#3780 refactor: dynamic mount test changes [GKE-GCSFuse Test migration]
  tools/integration_tests/read_cache/remount_test.go
  tools/integration_tests/util/mounting/dynamic_mounting/dynamic_mounting.go
Labels: remind-reviewers

#3844 feat(optimize profile): make the flag --profile visible in gcsfuse --help
  cfg/config.go
  cfg/params.yaml
Labels: execute-integration-tests, remind-reviewers

#3841 fix(ci): fix benchmark test log parsing for JUNIT XML generation.
  tools/integration_tests/improved_run_e2e_tests.sh
Labels: execute-integration-tests, remind-reviewers

#3842 feat(dns_cache): Guard HTTP/1 DNS cache enablement with a boolean flag
  cfg/config.go
  cfg/params.yaml
  cfg/validate.go
  cfg/validate_test.go
  cmd/root_test.go
Labels: remind-reviewers

#3843 style(metrics): Remove unnecessary whitespaces
  metrics/otel_metrics.go
  tools/metrics-gen/otel_metrics.tpl
Labels: remind-reviewers

#3845 refactor(cd): fixes in cd script for robustness
  tools/cd_scripts/e2e_test.sh
Labels: remind-reviewers

#3817 fix: Fix rename issue with new auth
  cfg/config.go
  cfg/params.yaml
  cmd/root_test.go
  internal/storage/storageutil/auth_client_option.go
  tools/integration_tests/util/mounting/static_mounting/static_mounting.go
Labels: execute-integration-tests, execute-integration-tests-on-zb

#3849 ci(long-haul): Clean up long-haul test code.
  perfmetrics/scripts/continuous_test/ml_tests/pytorch/v1_12/dino/build.sh
  perfmetrics/scripts/continuous_test/ml_tests/pytorch/v1_12/dino/continuous.cfg
  perfmetrics/scripts/continuous_test/ml_tests/pytorch/v2/dino/build.sh
  perfmetrics/scripts/continuous_test/ml_tests/pytorch/v2/dino/continuous.cfg
  perfmetrics/scripts/continuous_test/ml_tests/pytorch/v2_hns/dino/build.sh
  perfmetrics/scripts/continuous_test/ml_tests/pytorch/v2_hns/dino/continuous.cfg
  perfmetrics/scripts/continuous_test/ml_tests/run_and_manage_test.sh
  perfmetrics/scripts/continuous_test/ml_tests/tf/resnet/build.sh
  perfmetrics/scripts/continuous_test/ml_tests/tf/resnet/continuous.cfg
  perfmetrics/scripts/continuous_test/ml_tests/tf/resnet_hns/build.sh
  perfmetrics/scripts/continuous_test/ml_tests/tf/resnet_hns/continuous.cfg
  perfmetrics/scripts/ml_tests/pytorch/README-usage.md
  perfmetrics/scripts/ml_tests/pytorch/run_container.sh
  perfmetrics/scripts/ml_tests/pytorch/run_model.sh
  perfmetrics/scripts/ml_tests/pytorch/v1_12/dino/Dockerfile
  perfmetrics/scripts/ml_tests/pytorch/v1_12/dino/setup_host_and_run_container.sh
  perfmetrics/scripts/ml_tests/pytorch/v2/dino/Dockerfile
  perfmetrics/scripts/ml_tests/pytorch/v2/dino/setup_host_and_run_container.sh
  perfmetrics/scripts/ml_tests/tf/resnet/Dockerfile
  perfmetrics/scripts/ml_tests/tf/resnet/README.md
  perfmetrics/scripts/ml_tests/tf/resnet/setup_host_and_run_model.sh
  perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/resnet_runner.py
  perfmetrics/scripts/ml_tests/tf/resnet/setup_scripts/setup_container.sh
Labels: remind-reviewers

#3832 fix(streaming): Enhance streaming writes warning log messages and remove duplication of warning logs.
  internal/fs/inode/file.go
Labels: execute-integration-tests, remind-reviewers

#3854 docs: Update streaming writes troubleshooting documentation.
  docs/troubleshooting.md
Labels: remind-reviewers

#3856 docs: Update troubleshooting doc regarding error while setting readGlobalMaxBlocks to -1
  docs/troubleshooting.md
Labels: remind-reviewers
